### ISSUE TITLE
Pre-generate regex

### ISSUE THREAD

**Issue by m1kit** [m1kit/yalm-python#7]
This issue is a part of #1 .

Currently, the templates are normalized first, and then the var tags are parsed. However, this method may cause the regular expression contained in the var tag to be transformed during normalization. ~~In fact, the current implementation deals with this by skipping some of the normalization steps for templates.~~

I think it is better to parse var tags first, and then normalize only the plain text excluding regular expressions.

**Comment by anshuldutt21** [comment]
I think it would be difficult to use this approach since there would be many <<var>> tags in the template. You would be required to set flags as to where the <<var>> tags have been replaced with the regex. Inline libraries like re.escape wont work too in this case and you would have to write it manually. 
In the current implementation, when the escaping of characters occur, the regex in the match pos is altered and the hardcoded '\' used are replaced by '@' which are later converted back into '\'. So there isn't any loss of steps afaik. If there are any do tell me in the comments. I have also updated the documentation a little bit which you can check out that explains this thing.

**Comment by m1kit** [comment]
Note that when I mentioned parsing, I meant creating an AST-like tree structure, not replacing regular expressions.

My argument is that if we have a data structure that follows semantics of the license template, we don't need to worry about escaping.

**Comment by m1kit** [comment]
This approach would be easier if we had a structured template data. I'll try after completing #1

**Comment by m1kit** [comment]
I'd like to keep the regular expression in the template unnormalized since it is hard. This means that templates should not contain consecutive spaces. I think that's not a big deal.

**Comment by m1kit** [comment]
The big decision I made was not to modify the regular expressions included in the license template. This can cause a mismatch when the regular expression contains uppercase letters. However, technical factors have led me to this conclusion

e.g.

A regex `S` should be normalized to `s`, while `\S` should not be normalized to `\s`.

**Comment by m1kit** [comment]
I've been having a hard time handling white-spaces on the XML recently.
At the moment, I am considering parsing it based on the following rules:

#### 1. Any leading/trailing spaces in a tag are ignored (just like DOM/HTML)
```
Foo<tag>
  Bar
</tag>
Baz
```
is parsed as
```
FooBar Baz
```

#### 2. Only exception to the rule: optional tags
```
Foo <optional>Bar </optional>Baz
```
should be parsed as
```
Foo Bar Baz
```

not this:
```
Foo BarBaz
```

Leading/trailing whitespaces in an optional tag is included in a template.

**Comment by goneall** [comment]
> I've been having a hard time handling white-spaces on the XML recently.

I've had similar problems in the Java tools.  We added attributes to define if there are spaces before or after the `<alt...` text primarily to handle output formatting (see https://github.com/spdx/license-list-XML/blob/3c0d2e59b2576492b5423d4e74862491c4676b73/schema/ListedLicense.xsd#L268).  This attribute could be used as a hint if there are spaces - I'm not sure if it would matter for matching, however.

**Comment by m1kit** [comment]
That should help.
If `spacing` attribute is properly configured, I can just follow the instruction of it.

**Comment by goneall** [comment]
If the attribute isn't present, there should be a space before which is the default.
